spring.application.name=springsecurity

spring.datasource.url=jdbc:postgresql://localhost:5432/SpringSecurity
spring.datasource.username=postgres
spring.datasource.password=aayush


#show sql and format sql
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
