spring.application.name=springsecurity

spring.datasource.url=jdbc:postgresql://localhost:5432/SpringSecurity
spring.datasource.username=postgres
spring.datasource.password=aayush

spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8180/realms/springbank/protocol/openid-connect/certs


#show sql and format sql
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
